version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./migrations/up.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data

volumes:
  data:
